name: file_pod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  socket_io_client: ^3.1.2
  provider: ^6.1.1
  file_picker: ^10.3.3
  qr_flutter: ^4.1.0
  image_downloader_web: ^2.0.4
  clipboard: ^2.0.2
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/